from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/bookings/dashboard/', views.admin_booking_dashboard,
         name='admin_booking_dashboard'),
    path('admin/api/bookings/<int:booking_id>/<str:status>/',
         views.admin_update_booking_status, name='admin_update_booking_status'),
    path('admin/api/doctors/', views.admin_doctors_api, name='admin_doctors_api'),
    path('admin/api/doctors/add/', views.admin_add_doctor, name='admin_add_doctor'),
    path('admin/api/doctors/<int:doctor_id>/edit/',
         views.admin_edit_doctor, name='admin_edit_doctor'),
    path('admin/api/doctors/<int:doctor_id>/delete/',
         views.admin_delete_doctor, name='admin_delete_doctor'),
    path('admin/api/hospitals/', views.admin_hospitals_api,
         name='admin_hospitals_api'),
    path('admin/api/hospitals/add/',
         views.admin_add_hospital, name='admin_add_hospital'),
    path('admin/api/hospitals/<int:hospital_id>/edit/',
         views.admin_edit_hospital, name='admin_edit_hospital'),
    path('admin/api/hospitals/<int:hospital_id>/delete/',
         views.admin_delete_hospital, name='admin_delete_hospital'),
    path('admin/api/treatments/', views.admin_treatments_api,
         name='admin_treatments_api'),
    path('admin/api/treatments/add/',
         views.admin_add_treatment, name='admin_add_treatment'),
    path('admin/api/treatments/<int:treatment_id>/edit/',
         views.admin_edit_treatment, name='admin_edit_treatment'),
    path('admin/api/treatments/<int:treatment_id>/delete/',
         views.admin_delete_treatment, name='admin_delete_treatment'),
    path('admin/api/users/<int:user_id>/delete/',
         views.admin_delete_user, name='admin_delete_user'),
    path('doctor/profile/', views.doctor_profile, name='doctor_profile'),
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/portal/', views.patient_portal, name='patient_portal'),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('patient/medical-history/doctors/', views.patient_medical_history_doctors,
         name='patient_medical_history_doctors'),
    path('patient/medical-history/hospitals/', views.patient_medical_history_hospitals,
         name='patient_medical_history_hospitals'),
    path('patient/medical-history/treatments/', views.patient_medical_history_treatments,
         name='patient_medical_history_treatments'),
    path('patient/medical-history/reports/', views.patient_medical_history_reports,
         name='patient_medical_history_reports'),
    path('patient/submit-review/', views.submit_review, name='submit_review'),
    path('get_entities/<str:entity_type>/',
         views.get_entities, name='get_entities'),
    path('reviews/', views.reviews_page, name='reviews_page'),
    path('api/reviews/', views.reviews_api, name='reviews_api'),
    path('admin/api/reviews/<int:review_id>/delete/',
         views.admin_delete_review, name='admin_delete_review'),
    path('patient/reviews/<int:review_id>/delete/',
         views.patient_delete_review, name='patient_delete_review'),
    path('test-auto-login/', views.test_auto_login, name='test_auto_login'),
]
