# Generated by Django 4.2.24 on 2025-09-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_signature",
        ),
    ]
