# Generated by Django 5.2.6 on 2025-10-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_profile_picture"),
        ("payments", "0002_remove_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.userprofile",
            ),
        ),
    ]
