# Generated by Django 5.2.6 on 2025-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("INR", "INR")], default="USD", max_length=3
            ),
        ),
    ]
