services:
  - type: web
    name: takeopinion
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT takeopinion.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: takeopinion.settings_prod
      - key: SECRET_KEY
        generate: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,takeopinionclient.onrender.com