# Generated by Django 4.2.13 on 2025-09-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("flag_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("country", "name")},
            },
        ),
    ]
