# Generated by Django 4.2.24 on 2025-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Feedback is immediately public"
            ),
        ),
    ]
