# Generated by Django 4.2.24 on 2025-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_alter_feedback_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
