# Generated by Django 4.2 on 2026-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('raw_query', models.TextField()),
                ('extracted_keywords', models.JSONField(default=list)),
                ('extracted_conditions', models.JSONField(default=list)),
                ('report_text_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
