# Generated by Django 5.2.6 on 2025-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotelbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Enter an image URL instead of uploading a file",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hotelimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hotel_images/"),
        ),
    ]
