# Generated by Django 4.2.24 on 2025-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='aftercare_instructions',
            field=models.TextField(blank=True, default='Rest and recovery period,Medication schedule,Follow-up appointments,Activity restrictions'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='anesthesia_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='treatment',
            name='duration',
            field=models.CharField(blank=True, default='5-7 days', max_length=100),
        ),
        migrations.AddField(
            model_name='treatment',
            name='preparation_guidelines',
            field=models.TextField(blank=True, default='Consult your doctor,Stop certain medications,Complete medical tests,Fast before procedure'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='procedure_details',
            field=models.TextField(blank=True, default='This treatment involves a comprehensive approach to address your medical condition with the latest techniques and technology. The procedure is performed by highly qualified specialists in state-of-the-art facilities.'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='recovery_time',
            field=models.CharField(blank=True, default='2-3 weeks', max_length=100),
        ),
        migrations.AddField(
            model_name='treatment',
            name='review_count',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='treatment',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
