# Generated by Django 4.2.24 on 2025-09-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treatments", "0002_treatment_aftercare_instructions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="treatments.treatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment FAQ",
                "verbose_name_plural": "Treatment FAQs",
                "ordering": ["order"],
            },
        ),
    ]
