# Generated by Django 4.2.13 on 2025-09-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
    ]
