# Generated by Django 4.2.13 on 2025-09-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("about", models.TextField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
                ),
                ("is_takeopinion_choice", models.BooleanField(default=False)),
                (
                    "treatments",
                    models.ManyToManyField(
                        blank=True, related_name="hospitals", to="treatments.treatment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="hospitals.hospital",
                    ),
                ),
            ],
        ),
    ]
