# Generated by Django 4.2.13 on 2025-09-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitals",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitals",
                to="core.state",
            ),
        ),
    ]
