# Generated by Django 4.2.24 on 2025-09-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_hospital_address_hospital_awards_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitalmedia",
            name="video_url",
        ),
    ]
