# Generated by Django 4.2.24 on 2025-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0005_hospital_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
