# Generated by Django 5.2.6 on 2025-10-06 12:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0006_hospital_starting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                help_text="URL to hospital's profile/thumbnail picture",
                validators=[core.validators.validate_image_url],
            ),
        ),
        migrations.AlterField(
            model_name="hospitalmedia",
            name="image_url",
            field=models.URLField(
                blank=True, validators=[core.validators.validate_image_url]
            ),
        ),
    ]
