# Generated by Django 4.2.24 on 2025-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_patient_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
