# Generated by Django 4.2.24 on 2025-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
