# Generated by Django 4.2.24 on 2025-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_medicalreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="google_meet_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet link for video consultations",
                null=True,
            ),
        ),
    ]
