# Generated by Django 4.2.13 on 2025-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("key_points", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "hospitals",
                    models.ManyToManyField(
                        blank=True, related_name="doctors", to="hospitals.hospital"
                    ),
                ),
                (
                    "treatments",
                    models.ManyToManyField(
                        blank=True, related_name="doctors", to="treatments.treatment"
                    ),
                ),
            ],
        ),
    ]
