# Generated by Django 4.2.13 on 2025-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="awards",
            field=models.TextField(
                blank=True, help_text="Enter awards separated by new lines"
            ),
        ),
    ]
