# Generated by Django 4.2.24 on 2025-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctormedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the doctor's background and expertise",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="doctor",
            name="languages_spoken",
            field=models.CharField(
                blank=True,
                help_text="Languages spoken by the doctor, separated by commas",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="medical_license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="doctor",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="doctor",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="doctor",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
