# Generated by Django 4.2.24 on 2025-09-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_doctor_about_doctor_email_doctor_languages_spoken_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctormedia",
            name="video_url",
        ),
    ]
