# Generated by Django 4.2.24 on 2025-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_remove_doctormedia_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.URLField(
                blank=True, help_text="URL to doctor's profile picture"
            ),
        ),
    ]
