# Generated by Django 4.2.24 on 2025-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_doctor_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctormedia",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
