# Generated by Django 5.2.6 on 2025-10-06 12:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0007_doctormedia_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                help_text="URL to doctor's profile picture",
                validators=[core.validators.validate_image_url],
            ),
        ),
        migrations.AlterField(
            model_name="doctormedia",
            name="image_url",
            field=models.URLField(
                blank=True, validators=[core.validators.validate_image_url]
            ),
        ),
        migrations.AlterField(
            model_name="doctormedia",
            name="video_url",
            field=models.URLField(
                blank=True, validators=[core.validators.validate_youtube_url]
            ),
        ),
    ]
